build:
  environment:
    php:
      version: 7.2
  nodes:
    coverage:
      tests:
        before:
          - "cp .env.example .env"
          - "echo 'SLACK_END_POINT =your_webhook' > .env"
        override:
          - command: 'php ./vendor/bin/phpunit --coverage-clover=coverage'
            coverage:
              file: 'coverage'
              format: 'php-clover'

filter:
  excluded_paths:
    - 'vendor/*'
    - 'tests/*'