build:
  environment:
    php7.2:
      version: 7.2
    php7.3:
      version: 7.3
  tests:
    before:
      - "cp .env.example .env"
      - "echo 'SLACK_END_POINT =your_webhook' > .env"
    override:
      - command: 'php ./vendor/bin/phpunit --coverage'
        coverage:
          file: 'phpunit.xml'
          format: 'php-clover'

filter:
  paths:
    - 'src/*'
  excluded_paths:
    - 'vendor/*'
    - 'tests/*'