sudo: false

language: php

php:
  - 7.2
  - 7.3

before_script:
  - curl -sS http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction
  - cp .env.example .env

script:
  - ./vendor/bin/phpunit