language: php

php:
  - 7.2
  - 7.3

matrix:
  include:
    - env:
        - SLACK_END_POINT =https://hooks.slack.com/services/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

before_script:
  - composer install --prefer-source --no-interaction
  - cp .env.example .env

script:
  - phpunit