language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  include:
    - env:
        - SLACK_END_POINT =https://hooks.slack.com/services/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

before_script:
  - composer install --prefer-source --no-interaction

script:
  - phpunit